### ISSUE TITLE
Need STM32F103RC support please

### ISSUE THREAD

**Issue by youprint** [ARMmbed/stm32customtargets#30]
Hi
I need to update a program from MBED OS5 to MBED OS6, for that i will need a generic STM32F103RC working on the 6 version of MBED OS. i tested the RE but it's not working properly on my board.

for mbed os5 i'm using these files and it's working great :
https://github.com/scottalford75/Remora/tree/develop/Firmware/FirmwareSource/Remora-OS5/TARGET_STM32F103xC

please help

**Comment by jeromecoutant** [comment]
Hi

Please check https://github.com/ARMmbed/mbed-os/pull/15256

and https://github.com/ARMmbed/stm32customtargets/commit/a6a959aac1c979f2eabfa0c74f4d6d842cbeabe8

**Comment by jeromecoutant** [comment]
Hi @youprint 
I think I can close this one ?
Thx

**Comment by youprint** [comment]
yes of course thanks so much
