### ISSUE TITLE
Incomplete list of STM32WL5 modules

### ISSUE THREAD

**Issue by lyusupov** [ARMmbed/stm32customtargets#34]
[The STM32WL5 list](https://github.com/ARMmbed/stm32customtargets#stm32wl) does not include:
- Ebyte [E77 module](https://www.aliexpress.com/item/1005004550760072.html) and
- Olimex [BB-STM32WL](https://www.olimex.com/Products/IoT/LoRa/BB-STM32WL/) module and
- AcSip ST50H

**Comment by jeromecoutant** [comment]
Hi
I agree, this list is made by customer and user propositions :-)
Feel free to improve STM32WL targets support!
Thx
