### ISSUE TITLE
question

### ISSUE THREAD

**Issue by tcpipchip** [ARMmbed/stm32customtargets#35]
![image](https://user-images.githubusercontent.com/11488460/197657249-3deac12f-c6e7-4c41-8186-3efc793a2120.png)
Hi
can you help me about this error ?
Thanks
I followed your instructions 
https://github.com/hallard/RAK3172-Breakout#readme
thanks!!!

**Comment by jeromecoutant** [comment]
Hi
Did you make this part:
> open the file custom_targets.json from folder stm32customtargets and copy whole contents

@hallard

**Comment by tcpipchip** [comment]
Hi!!!
I tested in Mbed Studio and got problem. On Keil Studio Cloud still have problems!
![image](https://user-images.githubusercontent.com/11488460/197756088-24196ed5-6b99-4341-a4cb-b643515e5dd6.png)
Now i am having this error o Mbed Studio.
do you know that ?

**Comment by jeromecoutant** [comment]
@0xc0170

**Comment by hallard** [comment]
Could you pleas check in menu `help` then `check for tools updates` and paste version here?

Mine are
![image](https://user-images.githubusercontent.com/2471931/197773252-8c1f7725-5899-41d2-8c92-044ad258822d.png)

**Comment by tcpipchip** [comment]
good morning Team
![image](https://user-images.githubusercontent.com/11488460/197773940-0060d29e-464b-4f05-8b13-2520c8d7b502.png)

**Comment by tcpipchip** [comment]
> Hi Did you make this part:
> 
> > open the file custom_targets.json from folder stm32customtargets and copy whole contents
> 
> @hallard

yes!

**Comment by tcpipchip** [comment]
i will uninstall and install the MBED STUDIO...

**Comment by tcpipchip** [comment]
![image](https://user-images.githubusercontent.com/11488460/197788807-dee1d767-a117-41ff-adc2-ff1d80df588f.png)
Now compiles!
One more question, wich TARGET processor should i choose that use the STM32WL55?

**Comment by hallard** [comment]
Nice,

Depends on the board you use, hard to answer without knowing your hardware

**Comment by tcpipchip** [comment]
We are representative on South America of WISOL
Our Hardware use STM32WL55...
One of the list uses the STM32WL55 ?
On STM32 SDK LIB i use STM32WL55JC

**Comment by hallard** [comment]
In this case why are you using custom targets? did you tried Nucleo STM32WL55?

Just typing `WL55` into target selection search answer your question.

![image](https://user-images.githubusercontent.com/2471931/197796628-9c185b56-6aee-4819-8c2f-ff1d17875cc9.png)

**Comment by tcpipchip** [comment]
now show me Murata, where can i add the Custom Murata ?

**Comment by hallard** [comment]
`Murata Type ABZ` was the target selected when I've done the capture for you (it was the last I worked on). I clicked on the actual target (here `Murata Type ABZ`) that brings you target search list then just type target you need (in the capture `WL55`)

As far as I remember, no need custom target for `Murata Type ABZ`, it's built-in like `Nucleo-WL55JC`

**Comment by tcpipchip** [comment]
yes, you are right! It´s WL55JC
https://lom204-cli-wisol.blogspot.com/2022/10/wisol-lom204-mais-uma-opcao-de-comandos.html

**Comment by tcpipchip** [comment]
![image](https://user-images.githubusercontent.com/11488460/197805089-f4c56a11-63ee-424e-8461-0c0f5394f4b9.png)

**Comment by tcpipchip** [comment]
i will see if will compiles the ABZ to STM32WL55

**Comment by tcpipchip** [comment]
![image](https://user-images.githubusercontent.com/11488460/197808915-364a80d5-cee6-4a4f-a524-ce62ac5eae9e.png)

**Comment by tcpipchip** [comment]
do you know where is the path to perifpheral info, uart, spi, etc of Nucleo-WL55JC?

**Comment by tcpipchip** [comment]
getting progress here!
![image](https://user-images.githubusercontent.com/11488460/197818210-b03b6823-bc81-49df-ace7-fb748582277c.png)

**Comment by tcpipchip** [comment]
now i will do the config to see if send loRaWAN packages

**Comment by tcpipchip** [comment]
still not connect
working on sub-bands AU915

**Comment by hallard** [comment]
@tcpipchip,

We are not magician, we do not have any schematics of your board (may be because it's not wired like nucleo), nor configuration file `mbed_app.json` of your project. Requesting help need minimal information to share, all is linked and missing one part can't have reliable expertise.

Anyway if your target is NUCLEO-WL55 I suggest @jeromecoutant to close this issue because it's no more related to custom target except if you intend to add your custom board as a custom target.

**Comment by tcpipchip** [comment]
You help me a lot!
ok, only confirm wich class mbed use!
A,B or C ?

`  "target_overrides": {
        "*": {
            "platform.stdio-convert-newlines": true,
            "platform.stdio-baud-rate": 115200,
            "platform.default-serial-baud-rate": 115200,
            "mbed-trace.enable": false,
            "mbed-trace.max-level": "TRACE_LEVEL_DEBUG",
            "lora.over-the-air-activation": true,
            "lora.duty-cycle-on": true,
            "lora.phy": "AU915",
            "lora.device-eui": "{ 0x00, 0xX0, 0xE1, 0x15, 0xXX, 0xXX, 0xD8, 0x0X}",
            "lora.application-eui": "{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x99 }",
            "lora.application-key": "{ 0xFF, 0x9F, 0x13, 0xXX, 0x40, 0x18, 0x0A, 0xXX, 0x5D, 0x68, 0x46, 0xE0, 0xA0, 0x14, 0x69, 0x54 }"
        },`

and

 `"fsb-mask" = "{0xFF00, 0x0000, 0x0000, 0x0000, 0x0002}"`

**Comment by tcpipchip** [comment]
here datasheet
https://github.com/SeongJiIoT/LSM1x0A_SDK_LoRaWAN104

**Comment by tcpipchip** [comment]
here how is going the blog that i dont want to abort :)
https://lom204-cli-wisol.blogspot.com/2022/10/o-objetivo-deste-blog-e-mostrar-um-e.html

**Comment by hallard** [comment]
It's up to you to choose your class depending on your device needs.
https://os.mbed.com/docs/mbed-os/v6.15/apis/lora-tech.html

**Comment by jeromecoutant** [comment]
Issue is now followed with https://github.com/ARMmbed/mbed-os-example-lorawan/issues/243

**Comment by tcpipchip** [comment]
![image](https://user-images.githubusercontent.com/11488460/198097076-693eaa05-0279-432d-9d2c-e917f3e69f64.png)
Working now on LOM204A :)
